### ISSUE TITLE
[list] tasks

### ISSUE THREAD

**Issue by COnion505** [marks-share/marks-share#36]
# tasks

- [ ] user authentication
- [ ] user component
- [ ] user sign-up page
- [ ] user sign-up API
- [ ] user sign-in page
- [ ] user sign-in API
- [ ] bookmark component
- [ ] create bookmark page
- [ ] create bookmark API
- [ ] view own private bookmarks page
- [ ] get own private bookmarks API
- [ ] view public bookmarks page
- [ ] get public bookmarks API
- [ ] bookmark list component
- [ ] create bookmark list page
- [ ] create bookmark list API
- [ ] view bookmark list page
- [ ] get bookmark list API
